spring.application.name=employee-service
# Logging configuration
logging.level.root=INFO
logging.level.com.invex.employee_service=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN

# Console log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n